In [15]:
# ! pip install pandas
# ! pip install xlrd
# ! pip install openpyxl

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('data/SPA_DataCatalogue_260602_NDSAP-aligned.csv')
#df = pd.read_csv('data/SPA_DataCatalogue_260602_NDSAP-aligned.csv', dtype={'date__earliest': 'Int64', 'date__latest': 'Int64'})
df.head()

,id,title,description,keywords,sector,group,jurisdiction,frequency,granularity__spatial,granularity__temporal,date__earliest,date__latest,access_type,format,provider,reference,url,access_method
0,17,Administrative Boundary Database,Georeferenced Administrative Boundary Database...,"administrative, taluka, georeferenced",Administrative Context,NaN,India,unknown,cd block / town,one-time,NaN,2023.0,open,shapefile,Survey of india,"Survey of India (2024) Online Maps Portal, NA",https://onlinemaps.surveyofindia.gov.in/Digita...,Go to source URL
1,15,Administrative Setup Jaipur,"Name of Panchayat samiti, No. of Gram Panchaya...","Panchayat Samit, No. of Gram Panchayats, censu...",Administrative Context,Census handbook,Jaipur District,unknown,district,one-time,NaN,2011.0,open,printed table,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL
2,16,Cadastal Map,Boundary for individual plots based on ownersh...,cadastal map,Administrative Context,NaN,Rajasthan,unknown,state,one-time,NaN,2024.0,open,printed map,"Bhunaksha, rajasthan","Bhunaksha, NA",https://bhunaksha.rajasthan.gov.in/,Go to source URL
3,3,Evolution Of Jaipur Urban Extent,Growth of Jaipur's urban area over time,"Growth, Urban Area, Jaipur",Administrative Context,L&T Infra Engineering Transport Study,City level,unknown,region,one-time,1989,2014.0,private,printed map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available
4,2,Gram Panchayat Of Jaipur Region,Boundaries for Gram Panchayats in Jaipur Region.,"Gram panchayat, boundaries, Jaipur Region",Administrative Context,master plan map,Jaipur Urban Area (2018),unknown,region,one-time,NaN,2011.0,open,printed map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL

In [ ]:
# import dataset kpi linkage from xlsx
df_kpi = pd.read_csv('data/SPA_DataCatalogue_260602.csv')
df_kpi.rename(columns=
  {
  'ki_supplyofpublictransportvehicles':'A01', 
  'ki_publictransportaccessibility':'A02',
  'ki_walkability':'A03',
  'ki_coveragebycyclingfacilities':'A04', 
  'ki_coverageofthedrainagesystem':'A05',
  'ki_traineddrivers':'A06',
  'ki_transportrelatedinvestment':'A07', 
  'ki_localtrafficflow':'A08', 
  'ki_organisedroaduse':'A09', 
  'ki_parkingmanagement':'A10', 
  'ki_reductionofprivatevehicles':'B01',
  'ki_motorvehicletrafficreduction':'B02',
  'ki_declineinaccidents':'B03', 
  'ki_walkingandcycling':'B04',
  'ki_publictransportridership':'B05',
  'ki_lastmileuseofintermediatepublictransport':'B06', 
  'ki_welllitsteets':'A11', 
  } , inplace=True)

kpi_columns = ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'B01', 'B02', 'B03', 'B04', 'B05', 'B06']
df_kpi['linked_to_kpi'] = df_kpi.apply(lambda row: ','.join([kpi for kpi in kpi_columns if row[kpi] == 1]), axis=1)
df_kpi.head()

,id,theme,data_display_name,keep,description,keywords,exists,reference,reference table/fig/pgno,provider,...,kd_effectiveenforcement,kd_xnokpidom,kd_sustainablemobility,kd_inclusivemobility,kd_healthandsafety,kd_sustainabletransportfunding,format2,editable,update_freq2,linked_to_kpi
0,1,Administrative Context,Villages In Jaipur Region,True,Names of villages in Jaipur Region.,"Villages, Jaipur Region,",yes,"JDA (2011) Master Development Plan 2025, vol1","Heading 2.8, map on pg no. 109",JDA,...,False,False,False,False,False,False,printed map,False,unknown,
1,2,Administrative Context,Gram Panchayat Of Jaipur Region,True,Boundaries for Gram Panchayats in Jaipur Region.,"Gram panchayat, boundaries, Jaipur Region",yes,"JDA (2011) Master Development Plan 2025, vol1","Map 3-3, pg. 131",JDA,...,False,False,False,False,False,False,printed map,False,unknown,
2,3,Administrative Context,Evolution Of Jaipur Urban Extent,True,Growth of Jaipur's urban area over time,"Growth, Urban Area, Jaipur",yes,L&T Infra Engineering (2022) Comprehensive Tra...,"Figure 6-1, Pg 6-2",JDA,...,False,False,False,False,False,False,printed map,False,unknown,
3,4,Administrative Context,Zones And Wards In Jaipur,True,Boundaries for zones and wards in Jaipur (as p...,"Boundaries, Zones & Wards, Census 2001",yes,"JDA (2011) Master Development Plan 2025, vol1","Map 3-2, pg. 130",JDA,...,True,False,False,False,False,False,printed map,False,unknown,
4,5,Administrative Context,List Of Existing Towns With Present Population...,True,"List of existing town with present population,...","Existing Towns, Population (Present and Future...",yes,"JDA (2011) Master Development Plan 2025, vol1","Table 2-39, pg. 121",JDA,...,False,False,False,False,False,False,printed table,False,unknown,

In [7]:
# merge both datasets by id
df = pd.merge(df, df_kpi[['id','linked_to_kpi']], on='id', how='left')
df.head(20)

,id,title,description,keywords,sector,group,jurisdiction,frequency,granularity__spatial,granularity__temporal,date__earliest,date__latest,access_type,format,provider,reference,url,access_method,linked_to_kpi
0,17,Administrative Boundary Database,Georeferenced Administrative Boundary Database...,"administrative, taluka, georeferenced",Administrative Context,NaN,India,unknown,cd block / town,one-time,NaN,2023.0,open,shapefile,Survey of india,"Survey of India (2024) Online Maps Portal, NA",https://onlinemaps.surveyofindia.gov.in/Digita...,Go to source URL,
1,15,Administrative Setup Jaipur,"Name of Panchayat samiti, No. of Gram Panchaya...","Panchayat Samit, No. of Gram Panchayats, censu...",Administrative Context,Census handbook,Jaipur District,unknown,district,one-time,NaN,2011.0,open,printed table,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,
2,16,Cadastal Map,Boundary for individual plots based on ownersh...,cadastal map,Administrative Context,NaN,Rajasthan,unknown,state,one-time,NaN,2024.0,open,printed map,"Bhunaksha, rajasthan","Bhunaksha, NA",https://bhunaksha.rajasthan.gov.in/,Go to source URL,
3,3,Evolution Of Jaipur Urban Extent,Growth of Jaipur's urban area over time,"Growth, Urban Area, Jaipur",Administrative Context,L&T Infra Engineering Transport Study,City level,unknown,region,one-time,1989,2014.0,private,printed map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,
4,2,Gram Panchayat Of Jaipur Region,Boundaries for Gram Panchayats in Jaipur Region.,"Gram panchayat, boundaries, Jaipur Region",Administrative Context,master plan map,Jaipur Urban Area (2018),unknown,region,one-time,NaN,2011.0,open,printed map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
5,11,Jda Base Map,"Base map of JDA region, Jaipur","Base Map, JDA",Administrative Context,master plan map,Jaipur Development Authority (2018),unknown,region,one-time,NaN,2019.0,open,printed map,JDA,"JDA (2009) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,
6,10,Jda Zonal Plan,"Zonal Plan of JDA region, Jaipur dated 2018","Zonal Boundary, JDA",Administrative Context,master plan map,Jaipur Development Authority (2018),unknown,region,one-time,NaN,2018.0,open,printed map,JDA,"JDA (2018) Zonal Development Plan, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,
7,5,List Of Existing Towns With Present Population...,"List of existing town with present population,...","Existing Towns, Population (Present and Future...",Administrative Context,master plan data,Jaipur District,unknown,district,one-time,NaN,2001.0,open,printed table,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
8,13,Nagar Nigam Jaipur Greater Map,Nagar Nigam Jaipur Greater Map,Nagar Nigam Jaipur Greater Map,Administrative Context,master plan map,Nagar Nigam Jaipur Greater (2019),unknown,region,one-time,NaN,2019.0,open,printed map,JDA,"JDA (2011) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,
9,14,Nagar Nigam Jaipur Heritage Map,Nagar Nigam Jaipur Heritage Map,Nagar Nigam Jaipur Heritage Map,Administrative Context,master plan map,Nagar Nigam Jaipur Heritage (2019),unknown,region,one-time,NaN,2019.0,open,printed map,JDA,"JDA (2011) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,
10,6,Population Density Map Of Jaipur Region,Population density for Jaipur Region.,"Population density, Jaipur Region",Administrative Context,L&T Infra Engineering Transport Study,Jaipur District,unknown,district,one-time,NaN,2011.0,private,printed map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,
11,7,Population Density Of Jmc And Satellite Towns,Population density of JMC and Satellite Towns.,"Population density, JMC, Sattelite towns",Administrative Context,L&T Infra Engineering Transport Study,Jaipur Region,unknown,region,one-time,NaN,2018.0,private,printed map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,
12,1,Villages In Jaipur Region,Names of villages in Jaipur Region.,"Villages, Jaipur Region,",Administrative Context,master plan map,Jaipur District,unknown,district,one-time,NaN,2011.0,open,printed map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
13,12,Walled City Jaipur,Map of Jaipur Walled City,Wall city jaipur,Administrative Context,master plan map,Jaipur Wall City (1987),unknown,region,one-time,NaN,2019.0,open,printed map,JDA,"JDA (1987) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,
14,8,Ward Wise Population Density Of Jmc,Ward wise population density of JMC area.,"Wardwise Population, JMC area",Administrative Context,L&T Infra Engineering Transport Study,Jaipur Municipal Corporation,unknown,region,one-time,NaN,2011.0,private,printed map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,
15,4,Zones And Wards In Jaipur,Boundaries for zones and wards in Jaipur (as p...,"Boundaries, Zones & Wards, Census 2001",Administrative Context,master plan map,Jaipur District,unknown,district,one-time,NaN,2001.0,open,printed map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
16,9,Zoning Map- Jaipur District,Zoning and growth nodes in Jaipur District.,"Ecosensitive, Agriculture Dominant, Urban, Rur...",Administrative Context,master plan map,Jaipur District,unknown,district,one-time,NaN,2011.0,open,printed map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
17,24,Age-Wise Population And Sex Distribution,"Age groups,male and female distribution","Age Groups, Gender Distribution",Demographic Profile,NaN,Jaipur District,unknown,district,one-time,NaN,2001.0,open,printed table,"Directorate of Census Operations, Rajasthan","JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,
18,64,Decadal Change In Population Of Tahsils By Res...,"Tahsil, Population (2001 and 2011), Percentage...","Population change, tehsils data",Demographic Profile,Census handbook,Jaipur District,unknown,district,one-time,NaN,2011.0,open,xls/xlsx,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,
19,23,Decadal Growth Rate In Jaipur Region,Decadal population growth rate in JMC and Satt...,"Decadal Growth Rate, Population, JMC, Satellit...",Demographic Profile,L&T Infra Engineering Transport Study,JMC+Satellite towns,unknown,city,one-time,1991,2011.0,private,printed table,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,

In [8]:
# Change case for certain columns
df['group'] = df['group'].str.title()
df['sector'] = df['sector'].str.title()
df['frequency'] = df['frequency'].str.capitalize()
df['access_type'] = df['access_type'].str.capitalize()
df['description'] = df['description'].map(lambda x: x[0].upper() + x[1:] if isinstance(x, str) and len(x) > 0 else x) # Capitalize first letter 
df['keywords'] = df['keywords'].str.lower()

# Fix granularity values
df['granularity__spatial'] = df['granularity__spatial'].str.title()
df['granularity__temporal'] = df['granularity__temporal'].str.title()
df['granularity__spatial'] = df['granularity__spatial'].str.replace('Cd Block / Town', 'CD Block / Town', regex=False)

# Fix Format 
df['format'] = df['format'].str.title()
df['format'] = df['format'].map(lambda x:x.upper() if x in ['Csv', 'Json', 'Xls/xlsx'] else x)
df['format'] = df['format'].str.replace('Geotiff Image', 'GeoTIFF', regex=False)
df['format'] = df['format'].str.replace('Shapefile', 'ESRI Shapefile', regex=False)
df.head()

,id,title,description,keywords,sector,group,jurisdiction,frequency,granularity__spatial,granularity__temporal,date__earliest,date__latest,access_type,format,provider,reference,url,access_method,linked_to_kpi
0,17,Administrative Boundary Database,Georeferenced Administrative Boundary Database...,"administrative, taluka, georeferenced",Administrative Context,NaN,India,Unknown,CD Block / Town,One-Time,NaN,2023.0,Open,ESRI Shapefile,Survey of india,"Survey of India (2024) Online Maps Portal, NA",https://onlinemaps.surveyofindia.gov.in/Digita...,Go to source URL,
1,15,Administrative Setup Jaipur,"Name of Panchayat samiti, No. of Gram Panchaya...","panchayat samit, no. of gram panchayats, censu...",Administrative Context,Census Handbook,Jaipur District,Unknown,District,One-Time,NaN,2011.0,Open,Printed Table,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,
2,16,Cadastal Map,Boundary for individual plots based on ownersh...,cadastal map,Administrative Context,NaN,Rajasthan,Unknown,State,One-Time,NaN,2024.0,Open,Printed Map,"Bhunaksha, rajasthan","Bhunaksha, NA",https://bhunaksha.rajasthan.gov.in/,Go to source URL,
3,3,Evolution Of Jaipur Urban Extent,Growth of Jaipur's urban area over time,"growth, urban area, jaipur",Administrative Context,L&T Infra Engineering Transport Study,City level,Unknown,Region,One-Time,1989,2014.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,Document not yet published,Not currently available,
4,2,Gram Panchayat Of Jaipur Region,Boundaries for Gram Panchayats in Jaipur Region.,"gram panchayat, boundaries, jaipur region",Administrative Context,Master Plan Map,Jaipur Urban Area (2018),Unknown,Region,One-Time,NaN,2011.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,

In [9]:
df['format'].value_counts()

format
Printed Table     76
Printed Map       72
CSV               30
GeoTIFF           25
Xls/Xlsx          19
JSON               8
Chart              4
Vector Map         4
ESRI Shapefile     1
Name: count, dtype: int64

In [10]:
df['linked_to_kpi'].value_counts()

linked_to_kpi
                   164
B02                 19
A02                 13
B03                  9
B01                  7
B01,B02,B03          5
A10                  4
B02,B04,B05,B06      4
B05                  4
A07                  3
A09                  3
A01                  2
A05                  2
B04                  1
B06                  1
A03                  1
B02,B05              1
Name: count, dtype: int64

In [11]:
# Clean up non-working URLs (to Null)
df['url'] = df['url'].replace('Jaipur City Mobility Plan', 'https://cuts-ccier.org/pdf/jaipur-city-mobility-plan.pdf')
df['url'] = df['url'].replace('Document not yet published', None)
df['access_method'] = df['access_method'].replace('Not currently available', None)
df['frequency'] = df['frequency'].replace('Unknown', None)

In [12]:
# add url_download column for one row (showcase download)
# df.loc[df.id == 290, 'url_download'] = 'https://orca.casa.ucl.ac.uk/~jens/sparc-dash/download/census2011.zip'
# df[df.id == 290]

In [13]:
# Add column lastupdated_group into last 2 years, 5 years, 10 years, etc.
import datetime
current_year = datetime.datetime.now().year
def lastupdated_group(year, yearlist=[2,5,10,15,20]):
    if year == 'N/A':
        return 'N/A'
    counter = 0
    for i in yearlist:
        if current_year - year <= i:
            return f'Last {i} yrs'
        counter += 1
    return f'{yearlist[counter-1]+1} yrs or older'
  
df['lastupdate'] = df['date__latest'].apply(lastupdated_group)                           
df.head()

,id,title,description,keywords,sector,group,jurisdiction,frequency,granularity__spatial,granularity__temporal,date__earliest,date__latest,access_type,format,provider,reference,url,access_method,linked_to_kpi,lastupdate
0,17,Administrative Boundary Database,Georeferenced Administrative Boundary Database...,"administrative, taluka, georeferenced",Administrative Context,NaN,India,None,CD Block / Town,One-Time,NaN,2023.0,Open,ESRI Shapefile,Survey of india,"Survey of India (2024) Online Maps Portal, NA",https://onlinemaps.surveyofindia.gov.in/Digita...,Go to source URL,,Last 5 yrs
1,15,Administrative Setup Jaipur,"Name of Panchayat samiti, No. of Gram Panchaya...","panchayat samit, no. of gram panchayats, censu...",Administrative Context,Census Handbook,Jaipur District,None,District,One-Time,NaN,2011.0,Open,Printed Table,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,,Last 15 yrs
2,16,Cadastal Map,Boundary for individual plots based on ownersh...,cadastal map,Administrative Context,NaN,Rajasthan,None,State,One-Time,NaN,2024.0,Open,Printed Map,"Bhunaksha, rajasthan","Bhunaksha, NA",https://bhunaksha.rajasthan.gov.in/,Go to source URL,,Last 2 yrs
3,3,Evolution Of Jaipur Urban Extent,Growth of Jaipur's urban area over time,"growth, urban area, jaipur",Administrative Context,L&T Infra Engineering Transport Study,City level,None,Region,One-Time,1989,2014.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 15 yrs
4,2,Gram Panchayat Of Jaipur Region,Boundaries for Gram Panchayats in Jaipur Region.,"gram panchayat, boundaries, jaipur region",Administrative Context,Master Plan Map,Jaipur Urban Area (2018),None,Region,One-Time,NaN,2011.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,Last 15 yrs

In [14]:
# Put keywords column to the back
keywords = df.pop('keywords')
df['keywords'] = keywords
df.head(20)

,id,title,description,sector,group,jurisdiction,frequency,granularity__spatial,granularity__temporal,date__earliest,date__latest,access_type,format,provider,reference,url,access_method,linked_to_kpi,lastupdate,keywords
0,17,Administrative Boundary Database,Georeferenced Administrative Boundary Database...,Administrative Context,NaN,India,None,CD Block / Town,One-Time,NaN,2023.0,Open,ESRI Shapefile,Survey of india,"Survey of India (2024) Online Maps Portal, NA",https://onlinemaps.surveyofindia.gov.in/Digita...,Go to source URL,,Last 5 yrs,"administrative, taluka, georeferenced"
1,15,Administrative Setup Jaipur,"Name of Panchayat samiti, No. of Gram Panchaya...",Administrative Context,Census Handbook,Jaipur District,None,District,One-Time,NaN,2011.0,Open,Printed Table,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,,Last 15 yrs,"panchayat samit, no. of gram panchayats, censu..."
2,16,Cadastal Map,Boundary for individual plots based on ownersh...,Administrative Context,NaN,Rajasthan,None,State,One-Time,NaN,2024.0,Open,Printed Map,"Bhunaksha, rajasthan","Bhunaksha, NA",https://bhunaksha.rajasthan.gov.in/,Go to source URL,,Last 2 yrs,cadastal map
3,3,Evolution Of Jaipur Urban Extent,Growth of Jaipur's urban area over time,Administrative Context,L&T Infra Engineering Transport Study,City level,None,Region,One-Time,1989,2014.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 15 yrs,"growth, urban area, jaipur"
4,2,Gram Panchayat Of Jaipur Region,Boundaries for Gram Panchayats in Jaipur Region.,Administrative Context,Master Plan Map,Jaipur Urban Area (2018),None,Region,One-Time,NaN,2011.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,Last 15 yrs,"gram panchayat, boundaries, jaipur region"
5,11,Jda Base Map,"Base map of JDA region, Jaipur",Administrative Context,Master Plan Map,Jaipur Development Authority (2018),None,Region,One-Time,NaN,2019.0,Open,Printed Map,JDA,"JDA (2009) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,,Last 10 yrs,"base map, jda"
6,10,Jda Zonal Plan,"Zonal Plan of JDA region, Jaipur dated 2018",Administrative Context,Master Plan Map,Jaipur Development Authority (2018),None,Region,One-Time,NaN,2018.0,Open,Printed Map,JDA,"JDA (2018) Zonal Development Plan, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,,Last 10 yrs,"zonal boundary, jda"
7,5,List Of Existing Towns With Present Population...,"List of existing town with present population,...",Administrative Context,Master Plan Data,Jaipur District,None,District,One-Time,NaN,2001.0,Open,Printed Table,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,21 yrs or older,"existing towns, population (present and future..."
8,13,Nagar Nigam Jaipur Greater Map,Nagar Nigam Jaipur Greater Map,Administrative Context,Master Plan Map,Nagar Nigam Jaipur Greater (2019),None,Region,One-Time,NaN,2019.0,Open,Printed Map,JDA,"JDA (2011) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,,Last 10 yrs,nagar nigam jaipur greater map
9,14,Nagar Nigam Jaipur Heritage Map,Nagar Nigam Jaipur Heritage Map,Administrative Context,Master Plan Map,Nagar Nigam Jaipur Heritage (2019),None,Region,One-Time,NaN,2019.0,Open,Printed Map,JDA,"JDA (2011) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,,Last 10 yrs,nagar nigam jaipur heritage map
10,6,Population Density Map Of Jaipur Region,Population density for Jaipur Region.,Administrative Context,L&T Infra Engineering Transport Study,Jaipur District,None,District,One-Time,NaN,2011.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 15 yrs,"population density, jaipur region"
11,7,Population Density Of Jmc And Satellite Towns,Population density of JMC and Satellite Towns.,Administrative Context,L&T Infra Engineering Transport Study,Jaipur Region,None,Region,One-Time,NaN,2018.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 10 yrs,"population density, jmc, sattelite towns"
12,1,Villages In Jaipur Region,Names of villages in Jaipur Region.,Administrative Context,Master Plan Map,Jaipur District,None,District,One-Time,NaN,2011.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,Last 15 yrs,"villages, jaipur region,"
13,12,Walled City Jaipur,Map of Jaipur Walled City,Administrative Context,Master Plan Map,Jaipur Wall City (1987),None,Region,One-Time,NaN,2019.0,Open,Printed Map,JDA,"JDA (1987) Key Maps, NA",https://jda.rajasthan.gov.in/content/raj/udh/j...,Go to source URL,,Last 10 yrs,wall city jaipur
14,8,Ward Wise Population Density Of Jmc,Ward wise population density of JMC area.,Administrative Context,L&T Infra Engineering Transport Study,Jaipur Municipal Corporation,None,Region,One-Time,NaN,2011.0,Private,Printed Map,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 15 yrs,"wardwise population, jmc area"
15,4,Zones And Wards In Jaipur,Boundaries for zones and wards in Jaipur (as p...,Administrative Context,Master Plan Map,Jaipur District,None,District,One-Time,NaN,2001.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,21 yrs or older,"boundaries, zones & wards, census 2001"
16,9,Zoning Map- Jaipur District,Zoning and growth nodes in Jaipur District.,Administrative Context,Master Plan Map,Jaipur District,None,District,One-Time,NaN,2011.0,Open,Printed Map,JDA,"JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,Last 15 yrs,"ecosensitive, agriculture dominant, urban, rur..."
17,24,Age-Wise Population And Sex Distribution,"Age groups,male and female distribution",Demographic Profile,NaN,Jaipur District,None,District,One-Time,NaN,2001.0,Open,Printed Table,"Directorate of Census Operations, Rajasthan","JDA (2011) Master Development Plan 2025, vol1,...",https://jda.rajasthan.gov.in/content/dam/raj/u...,Go to source URL,,21 yrs or older,"age groups, gender distribution"
18,64,Decadal Change In Population Of Tahsils By Res...,"Tahsil, Population (2001 and 2011), Percentage...",Demographic Profile,Census Handbook,Jaipur District,None,District,One-Time,NaN,2011.0,Open,Xls/Xlsx,"Directorate of Census Operations, Rajasthan","Directorate of Census Operations, Rajasthan (2...",https://censusindia.gov.in/nada/index.php/cata...,Go to source URL,,Last 15 yrs,"population change, tehsils data"
19,23,Decadal Growth Rate In Jaipur Region,Decadal population growth rate in JMC and Satt...,Demographic Profile,L&T Infra Engineering Transport Study,JMC+Satellite towns,None,City,One-Time,1991,2011.0,Private,Printed Table,JDA,L&T Infra Engineering (2022) Comprehensive Tra...,None,None,,Last 15 yrs,"decadal growth rate, population, jmc, satellit..."

In [15]:
df.shape

(243, 20)

In [16]:
df.to_json('../../public/data/datacatalogue.json', orient='records', indent=4)